server {
    listen 20080;
    server_name localhost;

    location / {
        root /home/c646860306/daydayup_frontend;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /uploads/ {
        alias /home/c646860306/uploads/;
    }
}
